/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JToggleButton;

import model.Album;
import model.Song;
import model.PlayerMusic;


/**
 *
 * @author ASUS
 */
public class ArtistFrame extends javax.swing.JFrame {

    private PlayerMusic<ArtistFrame> playerMusic = new PlayerMusic<ArtistFrame>();
    private ArrayList fileList = new ArrayList();

    public PlayerMusic getPlayerMusic() {
        return playerMusic;
    }

    public void setPlayerMusic(PlayerMusic playerMusic) {
        this.playerMusic = playerMusic;
    }
    
    
    
    /**
     * Creates new form ArtistView
     */
    public ArtistFrame(String artistName) {
        initComponents();
        tv_nama.setText(artistName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        tv_nama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_album = new javax.swing.JList<String>();
        tv_current_album = new javax.swing.JLabel();
        tv_judul_lagu = new javax.swing.JLabel();
        btn_prev = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_pause = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_song_album = new javax.swing.JList<String>();
        btn_add_lagu = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_add_album = new javax.swing.JButton();
        btn_shuffle = new javax.swing.JToggleButton();
        btn_repeat = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tv_nama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tv_nama.setForeground(new java.awt.Color(255, 255, 255));
        tv_nama.setText("Nama");
        getContentPane().add(tv_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 43));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Album");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 40));

        jScrollPane1.setViewportView(list_album);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 147, 220));

        tv_current_album.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tv_current_album.setForeground(new java.awt.Color(255, 255, 255));
        tv_current_album.setText("Album");
        getContentPane().add(tv_current_album, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 240, 43));

        tv_judul_lagu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tv_judul_lagu.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tv_judul_lagu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btn_prev.setBackground(new java.awt.Color(255, 255, 255));
        btn_prev.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_prev.setForeground(new java.awt.Color(255, 102, 0));
        btn_prev.setText("◄|");
        getContentPane().add(btn_prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        btn_play.setBackground(new java.awt.Color(255, 255, 255));
        btn_play.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_play.setForeground(new java.awt.Color(255, 102, 0));
        btn_play.setText("►");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        getContentPane().add(btn_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        btn_next.setBackground(new java.awt.Color(255, 255, 255));
        btn_next.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_next.setForeground(new java.awt.Color(255, 102, 0));
        btn_next.setText("|►");
        getContentPane().add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        btn_pause.setBackground(new java.awt.Color(255, 255, 255));
        btn_pause.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_pause.setForeground(new java.awt.Color(255, 102, 0));
        btn_pause.setText("||");
        getContentPane().add(btn_pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jScrollPane2.setViewportView(list_song_album);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 70, 570, 330));

        btn_add_lagu.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_lagu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_add_lagu.setForeground(new java.awt.Color(255, 102, 0));
        btn_add_lagu.setText("Tambah Lagu");
        getContentPane().add(btn_add_lagu, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 30, 130, 30));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 102, 0));
        btn_logout.setText("Keluar");
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btn_add_album.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_album.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add_album.setForeground(new java.awt.Color(255, 102, 0));
        btn_add_album.setText("Tambah Album");
        getContentPane().add(btn_add_album, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 147, 30));

        btn_shuffle.setBackground(new java.awt.Color(255, 255, 255));
        btn_shuffle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_shuffle.setForeground(new java.awt.Color(255, 102, 0));
        btn_shuffle.setText("Shuffle");
        btn_shuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shuffleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_shuffle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        btn_repeat.setBackground(new java.awt.Color(255, 255, 255));
        btn_repeat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_repeat.setForeground(new java.awt.Color(255, 102, 0));
        btn_repeat.setText("Repeat");
        getContentPane().add(btn_repeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/beautiful-color-ui-gradients-backgrounds-peach.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList getFileList() {
        return fileList;
    }

    public void setFileList(ArrayList fileList) {
        this.fileList = fileList;
    }
    
    

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_shuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shuffleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_shuffleActionPerformed

    public void addActionListener(ActionListener a){
        btn_add_album.addActionListener(a);
        btn_add_lagu.addActionListener(a);
        btn_logout.addActionListener(a);
        btn_next.addActionListener(a);
        btn_pause.addActionListener(a);
        btn_play.addActionListener(a);
        btn_prev.addActionListener(a);
        btn_repeat.addActionListener(a);
        btn_shuffle.addActionListener(a);
        
    }
    
    public void addMouseListener(MouseListener m){
        list_album.addMouseListener(m);
        list_song_album.addMouseListener(m);
    }
    
    
    public JButton getBtn_add_album() {
        return btn_add_album;
    }

    public JButton getBtn_add_lagu() {
        return btn_add_lagu;
    }

    public JButton getBtn_logout() {
        return btn_logout;
    }

    public JButton getBtn_next() {
        return btn_next;
    }

    public JButton getBtn_pause() {
        return btn_pause;
    }

    public JButton getBtn_play() {
        return btn_play;
    }

    public JButton getBtn_prev() {
        return btn_prev;
    }

    public JToggleButton getBtn_repeat() {
        return btn_repeat;
    }

    public JToggleButton getBtn_shuffle() {
        return btn_shuffle;
    }

    public String getTv_current_album() {
        return tv_current_album.getText();
    }

    public void setTv_current_album(String tv_current_album) {
        this.tv_current_album.setText(tv_current_album);
    }

    public String getTv_judul_lagu() {
        return tv_judul_lagu.getText();
    }

    public void setTv_judul_lagu(String tv_judul_lagu) {
        this.tv_judul_lagu.setText(tv_judul_lagu); 
    }

    public String getTv_nama() {
        return tv_nama.getText();
    }

    public void setTv_nama(String tv_nama) {
        this.tv_nama.setText(tv_nama); 
    }

    public void setList_album(ArrayList<String> list_album) {
        
        // declaration and initialise String Array 
        String titles[] = new String[list_album.size()]; 
  
        // ArrayList to Array Conversion 
        for (int j = 0; j < list_album.size(); j++) { 
  
            // Assign each value to String array 
            titles[j] = list_album.get(j); 
        } 
        
        this.list_album.setListData(titles);
    }
    
    public void setList_song_album(ArrayList<Song> list_song) {
        
        // declaration and initialise String Array 
        String titles[] = new String[list_song.size()]; 
  
        // ArrayList to Array Conversion 
        for (int j = 0; j < list_song.size(); j++) { 
  
            // Assign each value to String array 
            
            titles[j] = list_song.get(j).getArtist() + " - " +list_song.get(j).getTitle(); 
        } 
        
        this.list_song_album.setListData(titles);
    }
    
    public void setList_file_album(ArrayList<Song> list_song) {
       
        for (int j = 0; j < list_song.size(); j++) { 
            fileList.add(new File(list_song.get(j).getPath()));
        } 
    }

    public JList<String> getList_album() {
        return list_album;
    }

    public JToggleButton getjToggleButton1() {
        return jToggleButton1;
    }

    public JList<String> getList_song_album() {
        return list_song_album;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_album;
    private javax.swing.JButton btn_add_lagu;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_pause;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_prev;
    private javax.swing.JToggleButton btn_repeat;
    private javax.swing.JToggleButton btn_shuffle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<String> list_album;
    private javax.swing.JList<String> list_song_album;
    private javax.swing.JLabel tv_current_album;
    private javax.swing.JLabel tv_judul_lagu;
    private javax.swing.JLabel tv_nama;
    // End of variables declaration//GEN-END:variables
}
