/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JToggleButton;
import model.PlayerMusic;
import model.Playlist;
import model.Song;

/**
 *
 * @author ASUS
 */
public class AudienceFrame extends javax.swing.JFrame {

    
    private PlayerMusic<AudienceFrame> playerMusic = new PlayerMusic<AudienceFrame>();
    private ArrayList fileList = new ArrayList();
    private ArrayList<String> playlistId = new ArrayList<>();
    private ArrayList<Playlist> playlistList = new ArrayList<Playlist>();

    public ArrayList<Playlist> getPlaylistList() {
        return playlistList;
    }

    public void setPlaylistList(ArrayList<Playlist> playlistList) {
        this.playlistList = playlistList;
    }
    
    
    
    public PlayerMusic<AudienceFrame> getPlayerMusic() {
        return playerMusic;
    }

    public void setPlayerMusic(PlayerMusic<AudienceFrame> playerMusic) {
        this.playerMusic = playerMusic;
    }

    public void setList_playlist(ArrayList<Playlist> list_playlist) {
        // declaration and initialise String Array 
        String names[] = new String[list_playlist.size()]; 
  
        // ArrayList to Array Conversion 
        for (int j = 0; j < list_playlist.size(); j++) { 
  
            // Assign each value to String array 
            names[j] = list_playlist.get(j).getPlaylistTitle();
            playlistId.add(list_playlist.get(j).getId());
        } 
        
        this.list_playlist.setListData(names);
    }

    
    
    
    /**
     * Creates new form ListenerView
     */
    public AudienceFrame(String audienceName) {
        initComponents();
        tv_nama.setText(audienceName);
    }
    
    public ArrayList getFileList() {
        return fileList;
    }

    public void setFileList(ArrayList fileList) {
        this.fileList = fileList;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        btn_prev = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_add_playlist = new javax.swing.JButton();
        tv_nama = new javax.swing.JLabel();
        btn_play = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_playlist = new javax.swing.JList<String>();
        btn_pause = new javax.swing.JButton();
        lb_daftar_lagu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_song_playlist = new javax.swing.JList<String>();
        tv_judul_lagu = new javax.swing.JLabel();
        btn_repeat = new javax.swing.JToggleButton();
        btn_shuffle = new javax.swing.JToggleButton();
        btn_add_lagu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_prev.setBackground(new java.awt.Color(255, 255, 255));
        btn_prev.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_prev.setForeground(new java.awt.Color(255, 102, 0));
        btn_prev.setText("◄|");
        getContentPane().add(btn_prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_logout.setText("Keluar");
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btn_add_playlist.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_playlist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_add_playlist.setForeground(new java.awt.Color(255, 102, 0));
        btn_add_playlist.setText("Tambah Playlist");
        getContentPane().add(btn_add_playlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, 40));

        tv_nama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tv_nama.setForeground(new java.awt.Color(255, 255, 255));
        tv_nama.setText("Nama");
        getContentPane().add(tv_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 43));

        btn_play.setBackground(new java.awt.Color(255, 255, 255));
        btn_play.setForeground(new java.awt.Color(255, 102, 0));
        btn_play.setText("►");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        getContentPane().add(btn_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        btn_next.setBackground(new java.awt.Color(255, 255, 255));
        btn_next.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_next.setForeground(new java.awt.Color(255, 102, 0));
        btn_next.setText("|►");
        getContentPane().add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Playlist");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 116, 40));

        list_playlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Semua Lagu" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list_playlist.setToolTipText("");
        jScrollPane1.setViewportView(list_playlist);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 210));

        btn_pause.setBackground(new java.awt.Color(255, 255, 255));
        btn_pause.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_pause.setForeground(new java.awt.Color(255, 102, 0));
        btn_pause.setText("||");
        getContentPane().add(btn_pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        lb_daftar_lagu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_daftar_lagu.setForeground(new java.awt.Color(255, 255, 255));
        lb_daftar_lagu.setText("Daftar Lagu");
        getContentPane().add(lb_daftar_lagu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 116, 43));

        jScrollPane2.setViewportView(list_song_playlist);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 69, 530, 330));

        tv_judul_lagu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tv_judul_lagu.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tv_judul_lagu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btn_repeat.setBackground(new java.awt.Color(255, 255, 255));
        btn_repeat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_repeat.setForeground(new java.awt.Color(255, 102, 0));
        btn_repeat.setText("Repeat");
        getContentPane().add(btn_repeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        btn_shuffle.setBackground(new java.awt.Color(255, 255, 255));
        btn_shuffle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_shuffle.setForeground(new java.awt.Color(255, 102, 0));
        btn_shuffle.setText("Shuffle");
        btn_shuffle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shuffleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_shuffle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        btn_add_lagu.setBackground(new java.awt.Color(255, 255, 255));
        btn_add_lagu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_add_lagu.setForeground(new java.awt.Color(255, 102, 0));
        btn_add_lagu.setText("Tambah lagu");
        getContentPane().add(btn_add_lagu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\TUBES\\PBO\\Mulay\\assets\\beautiful-color-ui-gradients-backgrounds-peach.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_shuffleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shuffleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_shuffleActionPerformed

    public void addActionListener(ActionListener a){
        btn_add_playlist.addActionListener(a);
        btn_add_lagu.addActionListener(a);
        btn_logout.addActionListener(a);
        btn_next.addActionListener(a);
        btn_pause.addActionListener(a);
        btn_play.addActionListener(a);
        btn_prev.addActionListener(a);
        btn_repeat.addActionListener(a);
        btn_shuffle.addActionListener(a);
        
    }
    
    public void addMouseListener(MouseListener m){
        list_playlist.addMouseListener(m);
        list_song_playlist.addMouseListener(m);
    }

    public JButton getBtn_add_lagu() {
        return btn_add_lagu;
    }

    public JButton getBtn_add_playlist() {
        return btn_add_playlist;
    }

    public JButton getBtn_logout() {
        return btn_logout;
    }

    public JButton getBtn_next() {
        return btn_next;
    }

    public JButton getBtn_pause() {
        return btn_pause;
    }

    public JButton getBtn_play() {
        return btn_play;
    }

    public JButton getBtn_prev() {
        return btn_prev;
    }

    public JToggleButton getBtn_repeat() {
        return btn_repeat;
    }

    public JToggleButton getBtn_shuffle() {
        return btn_shuffle;
    }

    public JList<String> getList_playlist() {
        return list_playlist;
    }

    public JList<String> getList_song_playlist() {
        return list_song_playlist;
    }

    public String getLb_daftar_lagu() {
        return lb_daftar_lagu.getText();
    }

    public void setLb_daftar_lagu(String lb_daftar_lagu) {
        this.lb_daftar_lagu.setText(lb_daftar_lagu);
    }

    public String getTv_judul_lagu() {
        return tv_judul_lagu.getText();
    }

    public void setTv_judul_lagu(String tv_judul_lagu) {
        this.tv_judul_lagu.setText(tv_judul_lagu);
    }

    public String getTv_nama() {
        return tv_nama.getText();
    }

    public void setTv_nama(String tv_nama) {
        this.tv_nama.setText(tv_nama);
    }

    public void setList_song_playlist(ArrayList list_song_playlist) {
        // declaration and initialise String Array 
        String names[] = new String[list_song_playlist.size()]; 
  
        // ArrayList to Array Conversion 
        for (int j = 0; j < list_song_playlist.size(); j++) { 
  
            // Assign each value to String array 
            names[j] = ((Song)list_song_playlist.get(j)).getArtist() + " - " + ((Song)list_song_playlist.get(j)).getTitle();
        } 
        
        this.list_song_playlist.setListData(names);
    }

    public Song addSong(String path){
        return null;
    }
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_lagu;
    private javax.swing.JButton btn_add_playlist;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_pause;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_prev;
    private javax.swing.JToggleButton btn_repeat;
    private javax.swing.JToggleButton btn_shuffle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_daftar_lagu;
    private javax.swing.JList<String> list_playlist;
    private javax.swing.JList<String> list_song_playlist;
    private javax.swing.JLabel tv_judul_lagu;
    private javax.swing.JLabel tv_nama;
    // End of variables declaration//GEN-END:variables
}
