/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tf_login_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_login_pass = new javax.swing.JPasswordField();
        btn_login_artist = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_move_daftar = new javax.swing.JButton();
        btn_login_audience = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\TUBES\\PBO\\Mulay\\assets\\ok-6-tapeten-9444-41-0.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tf_login_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 126, 61));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 131, 91));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASUK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 98, -1));
        getContentPane().add(tf_login_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 30));

        btn_login_artist.setBackground(new java.awt.Color(255, 255, 255));
        btn_login_artist.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_login_artist.setForeground(new java.awt.Color(255, 102, 0));
        btn_login_artist.setText("Masuk sebagai artis");
        getContentPane().add(btn_login_artist, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\TUBES\\PBO\\Mulay\\assets\\beautiful-color-ui-gradients-backgrounds-peach.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -110, 770, 190));

        btn_move_daftar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_move_daftar.setForeground(new java.awt.Color(255, 102, 0));
        btn_move_daftar.setText("Daftar");
        btn_move_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_move_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_move_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 400, 50));

        btn_login_audience.setBackground(new java.awt.Color(255, 255, 255));
        btn_login_audience.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_login_audience.setForeground(new java.awt.Color(255, 102, 0));
        btn_login_audience.setText("Masuk sebagai audience");
        btn_login_audience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_audienceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login_audience, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 50));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_audienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_audienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_login_audienceActionPerformed

    private void btn_move_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_move_daftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_move_daftarActionPerformed

    public JButton getBtn_login_artist() {
        return btn_login_artist;
    }

    public JButton getBtn_login_audience() {
        return btn_login_audience;
    }

    public String getTf_login_email() {
        return tf_login_email.getText();
    }

    public String getTf_login_pass() {
        return tf_login_pass.getText();
    }

    public void addActionListener(ActionListener a){
        btn_login_artist.addActionListener(a);
        btn_login_audience.addActionListener(a);
        btn_move_daftar.addActionListener(a);
    }
    
    public void showMessageDialog(String message){
        JOptionPane.showMessageDialog(null, message);

    }

    public JButton getBtn_move_daftar() {
        return btn_move_daftar;
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login_artist;
    private javax.swing.JButton btn_login_audience;
    private javax.swing.JButton btn_move_daftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_login_email;
    private javax.swing.JPasswordField tf_login_pass;
    // End of variables declaration//GEN-END:variables
}
