/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form Daftar
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_regis_pass = new javax.swing.JPasswordField();
        tf_regis_nama = new javax.swing.JTextField();
        tf_regis_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_regis_audience = new javax.swing.JButton();
        btn_regis_artist = new javax.swing.JButton();
        btn_move_masuk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DAFTAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 126, 67));
        getContentPane().add(tf_regis_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 244, 40));

        tf_regis_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_regis_namaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_regis_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 244, 40));
        getContentPane().add(tf_regis_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 244, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btn_regis_audience.setBackground(new java.awt.Color(255, 255, 255));
        btn_regis_audience.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_regis_audience.setForeground(new java.awt.Color(255, 102, 0));
        btn_regis_audience.setText("Daftar sebagai audience");
        btn_regis_audience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regis_audienceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regis_audience, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 220, 50));

        btn_regis_artist.setBackground(new java.awt.Color(255, 255, 255));
        btn_regis_artist.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_regis_artist.setForeground(new java.awt.Color(255, 102, 0));
        btn_regis_artist.setText("Daftar sebagai artis");
        getContentPane().add(btn_regis_artist, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 210, 50));

        btn_move_masuk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_move_masuk.setForeground(new java.awt.Color(255, 102, 0));
        btn_move_masuk.setText("Masuk");
        getContentPane().add(btn_move_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 440, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\TUBES\\PBO\\Mulay\\assets\\beautiful-color-ui-gradients-backgrounds-peach.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -160, 700, 240));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_regis_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_regis_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_regis_namaActionPerformed

    private void btn_regis_audienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regis_audienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regis_audienceActionPerformed

    public JButton getBtn_regis_artist() {
        return btn_regis_artist;
    }

    public JButton getBtn_regis_audience() {
        return btn_regis_audience;
    }

    public JButton getBtn_move_masuk() {
        return btn_move_masuk;
    }

    public String getTf_regis_email() {
        return tf_regis_email.getText();
    }

    public String getTf_regis_nama() {
        return tf_regis_nama.getText();
    }

    public String getTf_regis_pass() {
        return tf_regis_pass.getText();
    }

    public void addActionListener(ActionListener a){
        btn_regis_artist.addActionListener(a);
        btn_regis_audience.addActionListener(a);
        btn_move_masuk.addActionListener(a);
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_move_masuk;
    private javax.swing.JButton btn_regis_artist;
    private javax.swing.JButton btn_regis_audience;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_regis_email;
    private javax.swing.JTextField tf_regis_nama;
    private javax.swing.JPasswordField tf_regis_pass;
    // End of variables declaration//GEN-END:variables
}
